/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#003f4b',
        'primary-container': '#005868',
        'on-primary': '#ffffff',
        'on-primary-container': '#8bccdf',
        'on-primary-fixed': '#001f26',
        'on-primary-fixed-variant': '#004e5c',
        'primary-fixed': '#acecff',
        'primary-fixed-dim': '#8fd0e3',
        secondary: '#626200',
        'secondary-container': '#eaea25',
        'secondary-fixed': '#eaea25',
        'secondary-fixed-dim': '#cdcd00',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#686800',
        'on-secondary-fixed': '#1d1d00',
        'on-secondary-fixed-variant': '#494900',
        tertiary: '#003f4b',
        'tertiary-container': '#005868',
        'tertiary-fixed': '#acecff',
        'tertiary-fixed-dim': '#8fd0e3',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#8bccdf',
        'on-tertiary-fixed': '#001f26',
        'on-tertiary-fixed-variant': '#004e5c',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-bright': '#f7f9fc',
        'surface-container': '#eceef1',
        'surface-container-low': '#f2f4f7',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#1d6777',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3f484b',
        'on-background': '#191c1e',
        background: '#f7f9fc',
        outline: '#70797c',
        'outline-variant': '#bfc8cb',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f4',
        'inverse-primary': '#8fd0e3',
        // Custom accent
        accent: '#D8D800',
        'accent-dark': '#c4c400',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
