export const INITIAL_FORM_DATA = {
  orgName: "",
  rechtsform: "",
  bundesland: "",
  ansprechpartner: "",
  taetigkeit: "",
  naceCode: "",
  mitarbeiter: "",
  umsatz: "",
  bilanzsumme: "",
  oeffentlich: "nein",
  oeffentlichEbene: "",
  konzern: "nein",
  konzernName: "",
  konzernMA: "",
  konzernUmsatz: "",
  konzernBilanz: "",
  itUnabhaengig: "unbekannt",
  spiA1_ids: [],
  spiA2_ids: [],
  sondermerkmale: [],
  keinesSonder: false,
  zertifizierungen: "",
  // Lieferkette as structured object matching prueflogik.js input
  lieferkette: {
    hatBeziehung: "unbekannt",
    kundenSektoren: [],
    artLeistung: "",
    itZugriff: "nein",
    vertraglicheAnforderungen: "",
  },
};

export const STEP_LABELS = [
  "Start",
  "Allgemein",
  "Tätigkeit",
  "Größe",
  "Öffentlich",
  "Konzern",
  "Sondermerkmale",
  "Lieferkette",
];
