export const INITIAL_FORM_DATA = {
  orgName: "",
  rechtsform: "",
  bundesland: "",
  ansprechpartner: "",
  taetigkeit: "",
  naceCode: "",
  mitarbeiter: "",
  umsatz: "",
  bilanzsumme: "",
  oeffentlich: "nein",
  oeffentlichEbene: "",
  konzern: "nein",
  konzernName: "",
  konzernMA: "",
  konzernUmsatz: "",
  konzernBilanz: "",
  itUnabhaengig: "unbekannt",
  spiA1: [],
  spiA2: [],
  sondermerkmale: [],
  keinesSonder: false,
  zertifizierungen: "",
  vorfaelle: "nein",
  hinweise: "",
  lieferbeziehung: "unbekannt",
  lieferKunden: "",
  lieferSektoren: "",
  lieferAnforderungen: "nein",
  lieferLeistung: "",
  lieferZugriff: "nein",
};

export const STEP_LABELS = [
  "Start",
  "Allgemein",
  "Tätigkeit",
  "Größe",
  "Öffentlich",
  "Konzern",
  "Sondermerkmale",
  "Lieferkette",
];
